import os
import unittest
import sys

import inmembrane
import inmembrane.tests
from inmembrane import helpers
from inmembrane.plugins import tmbetadisc_rbf_web

class TestTmbetadisc_rbf(unittest.TestCase):
  def setUp(self):
    self.dir = os.path.join(
       os.path.abspath(
       os.path.dirname(inmembrane.tests.__file__)), 'tmbetadisc_rbf')

  def test_tmbetadisc_rbf(self):
    save_dir = os.getcwd()
    os.chdir(self.dir)

    helpers.silence_log(True)
    helpers.clean_directory('.', ['input.fasta'])
    
    self.params = inmembrane.get_params()
    self.params['fasta'] = "input.fasta"
    self.seqids, self.proteins = \
        helpers.create_proteins_dict(self.params['fasta'])
    tmbetadisc_rbf_web.annotate(self.params, self.proteins)
    
    self.expected_output = {
        'gi|107836852': {
          'sequence_length': 270, 
          'name': 'outer membrane protein HorF [Helicobacter pylori HPAG1]', 
          'seq': 'MKKFVVFKTLCLSVVLGNSLLAAEGSTEVQKQLEKPKEYKAVKGEKNAWYLGISYQVGQASQSVKNPPKSSEFNYPKFPVGKTDYLAVMQGLGLTVGYKQFFGEKRWFGARYYGFMDYGHAVFGANALTSDNGGACKLNEPCATKVGTMGNLSDMFTYGVGIDTLYNVINKEDASFGFFFGAQIAGNSWGNTTGAFLETKSPYKHTSYSLDPAIFQFLFNLGIRTHIGRHQEFDFGVKIPTINVYYFNHGNLSFTYRRQYSLYVGYRYNF', 
          'is_tmbetadisc_rbf': True, 
        },
        'gi|107837106': {
          'sequence_length': 326, 
          'name': 'heat shock protein [Helicobacter pylori HPAG1]', 
          'seq': 'MRARCSKKSSMRKEKIMTNFEKIIAQNRLKTNAVLTTYCVIFAFIGLLVDAIRINANDLGVALFKLITFQIFPTITTIMFLAAFVIIVVCIQNFSSIMLSGDEYKLIDTSKVLSSKENQIHRLLLELLEEAKLHFEPKLYIINAPYMNAFASGWDESNSLIALTSALIERLDKDELKAVIAHELSHIRHNDIRLTMCVGILSNIMLLVANFSVYFFMGNRKNSGANLARMILLLLQIVLPFLTLILQMYLSRTREYMADSGAAFLMHDNKPMIRALQKISNDYANNDYKGIDQNSTRSAAYLFNAEMFSTHPSIKNRIQSLSRRVI', 
          'is_tmbetadisc_rbf': False, 
        },
        'gi|107837101': {
          'sequence_length': 2417, 
          'name': 'vacuolating cytotoxin (VacA)-like protein [Helicobacter pylori HPAG1]', 
          'seq': 'MAFKKARLISRFISKGSFKLSKISKKIFTLNQILKCEKPLKCHKKTKSIKKLSNRNKSFLKASILLIGALGGLSHLRANECRYWSWSSWGYQDNIESGPNSPTHNSYCLFSSTQGSGTYYLNTLTTYSAGGASFTQKFNGGTLNVGGNIRFGGTGINGGDVGYITGTYDAQTINFNSSHLTTGNSYADGGGATLNFNAANNITINQASFDNSDAGAQKSYMNFKGSNIKVSGSSFKDDTDGGFSFSGNSNNSTISFNQTNFNQGTYNFSNSANLSFTNSAFNQGTYNFNSAQSVFENSSFNQGTYNFNSAQSVFENSAFNQGTYNFNGNASFDNDIFNQGTYNFNTSKVSFSGANTLNSSSPFASLKGSVSFGSDAVFNLNQTLNSNQTYDILTTNGTIQYGVYQSYLWDLINYKGDKAISHVEVGNNTYDVTFDINGQDETLQETFNKQSIITQFLGDDLQQQAQKTYQQDLSNSQSALNNAASDSKVANNDTGYTQSKNATVAKDAQGLENTNQKIQQDEQALEKDLAQIKQLANSTTGFNQQAFNQAQSTEQQDEQTLQNEENTFNIEQESLDKAIANAKHTSPTPSPTPTPTKHTAQNTPPNKVSPTPTPPTQNLPTTNVWNGVYWLQNQTYSKQGVYYIDPNLSGQSGQSANTLSTYTANLFGRSFGVNIQNGTLIIGNNTESVNDNGLIWIGHGGFGYITGTFSAANIYLTNNFKTGEGVSNSDGGGANITFKASDNITMDGLNYNDAETVTKMIQTGASQHSYAAFDALNNISVTNSSFSDMTWGKFSFSAKNISFSNASFSGFTNPGGSSVISANASNSLSFINSRLNGGAVYNLWANSLIFNNTQAVFNVLHSRGTSNFNATTQLLGNTNFTLSSQSLLNFNGDTTLQNNANITLGNKSQAAFKNSLTLDNDSNLSLDNQSVLNANGASAFNNQASLNIYNGSQATFKSLFFNGGTLSLNASSKLNASSASFSNNTTINLDDSVLSASNTSSLNANINFQGASQADFGGNTTINTASFNFDSASSLSFNNLTANGALNFNGYTPSLTKALMSVSGQFVLGNNGDINLSDINIFDNITKSVTYNILNAQKGITGISGANGYEKILFYGMKIQNATYSGNNNIQTWSFINPLNSSQIIQESIKNGDLTIEILNNPNSASNTIFNIAPELYNYQASKQNPTGYSYDYSDNQAGTYYLTSNIKGLFTPKGSQTPQTPGTYSPFNQPLNSLNIYNKGFSSENLKTLLGILSQNSATLKEMIESNQLDNITNINEVLQLLDKIKITQTQKQALLETINHLTDNINQTFNNGNLIIGATQDNVTNSTSSIWFGGNGYSSPCALDSATCSSFRNTYLGQLLGSTSPYLGYINADFKAKSIYITGTIGSGNAFESGGSADVTFQSTNNLVLNKANIEAQATDNIFNLLGQEGIDKIFNQGNLANVLSQMAMEKIKQAGGLGNFIENALSPLSKELPASLQDETLGQLIGQNNLDDLLNNSGVMNAIQNIISKKLSIFGNFVTPSIIENYLAKQSLKSMLDDKGLLNFIGGYIDASELSSILSVILKDITNPPTSLQKDIGVVANDLLNEFLGQDVIKKLESQELVNNIINNIISQGGLSGVYNQGLGSVLPPSLQNALKENDLGALLSPRGLHDFWQKGYFNFLSNGYVFVNNSSFSNATGGSLNFVANKSIIFDGDNTIDFSKYQGALIFASNDVSNINITTLNATNGLSLNAGLNNVSVQKGEICVNLANCPTTKNSSSTNSSVTPTNESLSVHANSFTFLGVIASNGAIDLSQVKNNSVIGTLNLNENATLQANNLTIANAFNNASNSTANINGDFTLNQQATLSTNASGLNVMGNFNSYGDLVFNLSHSVSHAIINAQGSATIMANNNNPLIQFNTSSKETGTYTLINSAKAIYYGYNDQITGGSSLDNYLKLYALIDINGKHMVMTDNGLTYNGQAVNIKDGGLVVGFKDSQNQYIYTSILYNKVKIAVSNDPINNLQAPTLKQYIAQIQGVQSVDSIDQVGGNQAINWLNKIFETKGSPLFAPYYLESHSTKDLTTIAGDIANTLEVIANPNFKNDATNILQINTYTQQMSRLAKLSDTSTFASADFHERLEALKNKRFADAIPNAMDVILKYSQRNRVKNNVWATGVGGASFINGGTGTLYGINVGYDRFIKGVIVGGYAAYGYSGFHGNITQSGSSNVNMGVYSRAFIKRSELTMSLNETWGYNKTFINSYDPLLSIINQSYRYDTWTTNAKINYGYDFMFKDKSVIFKPQVGLAYYYIGLSGLRGIMDDPIYNQFRANADPNKKSVLTINFALESRHYFNKNSYYFVIADVGRDLFINSMGDKMVRFIGNNTLSYRDGGRYNTFASIITGGEIRLFKTFYVNAGIGARFGLDYKDINITGNIGMRYAF', 
          'is_tmbetadisc_rbf': True, 
        },
        'gi|107836588': {
          'sequence_length': 240, 
          'name': 'hypothetical protein HPAG1_0390 [Helicobacter pylori HPAG1]', 
          'seq': 'MGLKKRAILWSLMGFYAGLNALDYDTLDPKYYKYIKYYKAYEDKEVEELIRDLKRANAKSGLILGINTGFFYNHEIMVRTNSSSITGNILNYLFAYGLRFGYQTFRPSFFARLVKPNIIGRRIYIQYYGGAPKKAGFGSVGFQSVMLNGDFLLDFPLPFVGKYLYMGGYMGLGLGVVAHGVNYTAEWGMSFNAGLALTVLEKNRIEFGFKILNNFPFLQSNSSKETWWGAIASIGYQYVF', 
          'is_tmbetadisc_rbf': True, 
        },
        'gi|107837107': {
          'sequence_length': 180, 
          'name': 'GTP cyclohydrolase I [Helicobacter pylori HPAG1]', 
          'seq': 'MENFFNQFFENIGEDKNREGLKETPKRVQELWKFLYKGYKEDPRVALKSAYFQGVCDEMIVAQNIEFYSTCEHHLLPFLGNISLGYIPKEKIVGISAIAKLIEIYSKRLQIQERLTTQITETFDEIIEPRGVIVVCEAKHLCMSMQGVQKQNAIIKTSVLRGLFKKDPKTRAEFMQLLKS', 
          'is_tmbetadisc_rbf': False, 
        },
      }

    #helpers.print_proteins(self.proteins)
    
    self.assertEqual(self.proteins, self.expected_output)

    os.chdir(save_dir)


if __name__ == '__main__':
  unittest.main()
