FROM continuumio/miniconda

RUN apt-get -y update && \
    apt-get -y install build-essential tcsh && \
    apt-get -y install blast2 && \
    apt-get -y clean && \
    pip install -U pip

RUN conda config --add channels defaults && \
    conda config --add channels conda-forge && \
    conda config --add channels bioconda

# The blast-legacy conda package is segfaulting for me, so we use that apt-get version
# RUN conda install blast-legacy==2.2.22 hmmer==3.1b2
RUN conda install hmmer==3.1b2

# Ideally this would be a data container, but Swissprot is pretty small, it's
# more convenient just to back it into the container in this instance
RUN mkdir -p /databases/blast && \
    cd /databases/blast && \
    wget ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz && \
    wget ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/reldate.txt && \
    gunzip uniprot_sprot.fasta.gz && \
    formatdb -p T -n uniprot_sprot -t uniprot_sprot -i uniprot_sprot.fasta && \
    rm uniprot_sprot.fasta

ENV APPS /software/apps
RUN mkdir -p ${APPS}
WORKDIR ${APPS}
RUN curl "http://bioinfadmin.cs.ucl.ac.uk/downloads/memsat/memsat3/memsat3.0.tar.gz" | tar xvz && \
    cd memsat/src && \
    make && \
    make install && \
    sed -i '/set dbname = /c\set dbname = \/databases\/blast\/uniprot_sprot' ${APPS}/memsat/runmemsat && \
    sed -i '/set ncbidir = /c\set ncbidir = \/usr\/bin' ${APPS}/memsat/runmemsat && \
    sed -i '/set execdir = /c\set execdir = \/software\/apps\/memsat\/bin' ${APPS}/memsat/runmemsat && \
    sed -i '/set datadir = /c\set datadir = \/software\/apps\/memsat\/data' ${APPS}/memsat/runmemsat && \
    ln -s ${APPS}/memsat/runmemsat /usr/bin/runmemsat

# Unfortunately SignalP, LipoP and TMHMM have inconvenient science-hostile licensing.
# If you've acquired and untared the package, modified the `signalp` Perl script such that:
# $ENV{SIGNALP} = /software/apps/signalp-4.1
# this might work.
# COPY ./signalp-4.1 ${APPS}/signalp-4.1
# RUN ln -s ${APPS}/signalp-4.1/signalp /usr/bin/signalp

COPY . ${APPS}/inmembrane
WORKDIR ${APPS}/inmembrane
RUN pip install -U -r requirements.txt && pip install -e .

RUN mkdir /data
WORKDIR /data
# ENV PATH ${APPS}/memsat:${PATH}
ENTRYPOINT ["inmembrane_scan"]
# CMD ["-t"]
# CMD ["--help"]
